drop table if exists t_merchants;
CREATE TABLE `t_merchants` (
  `Fmid` int(10) unsigned NOT NULL COMMENT '商家的ID',
  `Fm_name` varchar(64) NOT NULL COMMENT '商家的名称',
  `Fm_desc` varchar(255) NOT NULL COMMENT '商家的关键词描述',
  `Fm_detail` varchar(4096) NOT NULL COMMENT '商家的详细描述，后面看需要可以改成text类型存放html格式数据',
  `Fuin` int(10) unsigned NOT NULL default '0' COMMENT '商家的qq号码',
  `Fwxid` varchar(64) NOT NULL default '' COMMENT '商家的微信号码',
  `Femail` varchar(64) NOT NULL default '' COMMENT '商家的服务邮箱',
  `Fwbtype` int(10) unsigned NOT NULL default '0' COMMENT '商家的微博类型，新浪微博或者腾讯微博',
  `Fwbid` varchar(64) NOT NULL default '' COMMENT '商家的微博帐号',
  `Fmobile0` varchar(16) NOT NULL default '' COMMENT '商家的手机号码',
  `Fmobile1` varchar(16) NOT NULL default '' COMMENT '商家的手机号码',
  `Fphone0` varchar(16) NOT NULL default '' COMMENT '商家的电话号码',
  `Fphone1` varchar(16) NOT NULL default '' COMMENT '商家的电话号码',
  `Fphone2` varchar(16) NOT NULL default '' COMMENT '商家的电话号码',
  `Fproperty` bigint(20) unsigned default '0' COMMENT '商家的用户属性',
  `Fdz_title` varchar(255) default '' COMMENT '工卡优惠的内容描述，目前先是一个文字串',
  `Fdz_detail` varchar(4096) default '' COMMENT '详细工卡优惠的内容描述，目前先是一个文字串',
  `Fcity_id` int(10) unsigned default '0' COMMENT '城市的Id',
  `Fcity_cn` varchar(10) default '' COMMENT '城市的中文名，比如深圳，广州',
  `Fcity_py` varchar(10) default '' COMMENT '城市的中文拼音，比如shenzhen，guangzhou',
  `Fcity_py_sub` varchar(10) default '' COMMENT '城市的中文拼音简写，比如sz，gz',
  `Flongitude` int(10) unsigned default '0' COMMENT '所在位置的经度',
  `Flatitude` int(10) unsigned default '0' COMMENT '所在位置的纬度',
  `Fposition` varchar(1024) default '' COMMENT '商家所在的地址位置文字描述',
  `Fcbd` varchar(64) default '' COMMENT '商家所在的商圈位置文字描述',
  `Fimg0` varchar(64) default '' COMMENT '商家店铺图片，默认这张图为主图',
  `Fimg1` varchar(64) default '' COMMENT '商家店铺图片',
  `Fimg2` varchar(64) default '' COMMENT '商家店铺图片',
  `Fimg3` varchar(64) default '' COMMENT '商家店铺图片',
  `Fimg4` varchar(64) default '' COMMENT '商家店铺图片',
  `Fcard_img` varchar(64) default '' COMMENT '商家会员卡图片',
  `Faverage_cost` int(10) unsigned default '0' COMMENT '商家的人均消费',
  `Fscore` int(10) unsigned default '0' COMMENT '总体评价得分',
  `Fscore_tasts` int(10) unsigned default '0' COMMENT '味道评价得分',
  `Fscore_env` int(10) unsigned default '0' COMMENT '环境评价得分',
  `Fscore_service` int(10) unsigned default '0' COMMENT '服务评价得分',
  `Findex_score` int(10) unsigned default '0' COMMENT '商家的排序因子，根据排序因子搜索排序',
  `Fstatus` int(10) unsigned default '0' COMMENT '商家的状态',
  `Fadd_time` int(10) unsigned default '0' COMMENT '商家的添加时间',
  `Fmodify_time` int(10) unsigned default '0' COMMENT '商家的修改时间',
  UNIQUE KEY `Fmid` (`Fmid`),
  UNIQUE KEY `Fm_name` (`Fm_name`)
) ENGINE=Innodb DEFAULT CHARSET=utf8;